name: GitHell

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Ensure abyss folder exists
        run: mkdir -p abyss

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Track execution
        id: execution_data
        run: |
          if [ -f abyss/README.yml ]; then
            execution_count=$(grep -oP '(?<=Execution Count: )\d+' abyss/README.yml | tail -1)
            execution_count=$((execution_count + 1))
          else
            execution_count=1
          fi
          echo "execution_count=$execution_count" >> $GITHUB_ENV

      - name: Commit and Push Changes
        run: |
          git config user.name "Jyrrel"
          git config user.email "jyrrel789@gmail.com"
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          count=0
          while [ $count -lt 1000 ]; do
            commit_id=$(cat /proc/sys/kernel/random/uuid)
            total_commits=$(git rev-list --count HEAD)

            echo "  ________.__  __     ___ ___         .__  .__   " > abyss/README.yml
            echo " /  _____/|__|/  |_  /   |   \\   ____ |  | |  |  " >> abyss/README.yml
            echo "/   \\  ___|  \\   __\\/    ~    \\_/ __ \\|  | |  |  " >> abyss/README.yml
            echo "\\    \\_\\  \\  ||  |  \\    Y    /\\  ___/|  |_|  |__" >> abyss/README.yml
            echo " \\______  /__||__|   \\___|_  /  \\___  >____/____/ " >> abyss/README.yml
            echo "        \\/                 \\/       \\/            " >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            echo "The abyss grows deeper with each commit." >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml
            echo "Commit ID: $commit_id" >> abyss/README.yml
            echo "Commit: $total_commits" >> abyss/README.yml
            echo "Execution Count: ${{ env.execution_count }}" >> abyss/README.yml
            echo "Last Execution Time: $current_time" >> abyss/README.yml
            echo "----------------------------------------------------" >> abyss/README.yml

            git add abyss/README.yml
            git commit -S -m "🌑 The abyss has no bottom... (Total commits: $total_commits, Executions: ${{ env.execution_count }}, Last run: $current_time)"
            count=$((count+1))
          done
          
          git push
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
